name: 'dkr_pub'
description: 'github docker container action to build, tag, and publish docker images to remote repositories '
inputs:
  name:
    description: 'docker image name'
    required: true
  username:
    description: 'remote container registry username'
    required: true
  password:
    description: 'remote container registry password'
    required: true
  registry:
    description: 'remote container registry url'
    default: ""
runs:
  using: 'docker'
  image: 'docker://kennylouie/dkr_pub:0.0.1'
  args:
    - ${{ inputs.name }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.registry }}
branding:
  icon: 'anchor'
  color: 'orange'
